name: Security Scan

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
          tar -xvzf gitleaks_8.18.2_linux_x64.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks (Secret Scanning)
        run: gitleaks detect --source . --report-format json --report-path gitleaks-report.json

      - name: Ensure Node is installed
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk (SCA)
        run: snyk test --json > snyk-report.json

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: scan-reports
          path: |
            gitleaks-report.json
            snyk-report.json
