name: Security Scan

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks (Secret Scanning)
        run: gitleaks detect --source . --report-format json --report-path gitleaks-report.json

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk (SCA)
        run: snyk test --json > snyk-report.json

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: scan-reports
          path: |
            *.json
